### ISSUE TITLE
Opinion about CSS Modules?

### ISSUE THREAD

**Issue by pigoz** [alexmingoia/pux-starter-app#16]
I think CSS Modules is a great idea to produce CSS that is scoped to the current component. Is anyone interested in it?

The upside is Webpack has really great tooling with css modules, the style loader, post css, etc. But of course it's not type safe (like `purescript-css`).

**Comment by alexmingoia** [comment]
I would recommend using the `style` element or `style` attribute to do scoped CSS. See https://www.purescript-pux.org/docs/css
