### ISSUE TITLE
depricated warnings

### ISSUE THREAD

**Issue by rosenk** [alexmingoia/pux-starter-app#19]
on npm start I've got many warning of the  type:
 Class import from <something> uses deprecated syntax that omits the 'class' keyword

and also:
Module <something> has unspecified imports, consider using the explicit form

**Comment by alexmingoia** [comment]
This is from the PureScript compiler. In 0.8.0 it started warning about unqualified imports, and most of the libraries have not been updated. On the first compilation pass, you'll get lots of warnings. Subsequent compiles should not show the same warnings. This should be changing in PureScript 0.9.0 as well.

**Comment by rosenk** [comment]
I don't get it. These compiler warnings are meaningful, why not we just fix them?

**Comment by alexmingoia** [comment]
None of the warnings come from pux or pux-starter-app, they are all from libraries used by pux and pux-starter-app. Eventually, they will all be fixed so as to not produce warnings.
