### ISSUE TITLE
Page is simply "dist/index.html" on fresh install

### ISSUE THREAD

**Issue by Mr-Wallet** [alexmingoia/pux-starter-app#22]
Following this instructions on Node 5.11.1, the page at localhost:3000 is plaintext: `dist/index.html`
If I add a slash and some letters e.g. `localhost:3000/dist` then I get something resembling the starter app but with a 404 instead of the increment/decrement area.

There were no errors or warnings that I noticed. This is on Windows 8, and my colleagues suspect some kind of windows-specific webpack weirdness.

**Comment by endeavour** [comment]
This happens for me too :( (Windows 10)

**Comment by dariooddenino** [comment]
Same on Windows 10.
Delete `static\index.html` and it should work :) I had to remove the clean task too, as rimraf gave me a lot of issues with locked resources!

**Comment by alexmingoia** [comment]
Can anyone confirm if this is still happening with the latest version of pux and pux-starter-app?

**Comment by dariooddenino** [comment]
It's not happening for me with the latest version :)
