### ISSUE TITLE
Hot reloading doesn't work

### ISSUE THREAD

**Issue by ianthehenry** [alexmingoia/pux-starter-app#25]
On a clean clone of the `pux-starter-app`, after running `npm install`, the following error occurs when making changes to source files. The hot module replacement sees this error and triggers a full page refresh, but you can see the error if you set "Preserve log" in the Chrome dev console.

```
Error: EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.
```

This prevents hot reloading from ever working, as the HMR runtime will always do a full page refresh, blowing out all your state.

**Comment by sleexyz** [comment]
Issue fixed by upgrading the following packages to the following versions:

```
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2"
```

I'll create a PR
