### ISSUE TITLE
Use Hyper instead of Express

### ISSUE THREAD

**Issue by alexmingoia** [alexmingoia/pux-starter-app#31]
The HTTP server should use purescript-hyper instead of purescript-express. It's the new hotness.

**Comment by owickstrom** [comment]
Happy to help if there's anything! :)

**Comment by alexmingoia** [comment]
You're welcome to take a stab at it if you want. I won't be able to get to this for a while. Also might want to wait for alexmingoia/purescript-pux#116

[src/Server.purs](https://github.com/alexmingoia/pux-starter-app/blob/master/src/Server.purs) would need to be rewritten, along with some other alternative to using webpack's express middleware in [webpack.config.client.js](https://github.com/alexmingoia/pux-starter-app/blob/master/webpack.config.client.js#L94-L114)

It shouldn't be too hard... all the HTTP server is used for is to render the app and serve some static assets. Hot-reloading can make things tricky.

**Comment by alexmingoia** [comment]
The newest release uses Hyper and works with PureScript 0.11
