### ISSUE TITLE
npm start throws error regarding webpack config

### ISSUE THREAD

**Issue by Zenleaf** [alexmingoia/pux-starter-app#8]
Hi,
I get this error when trying to run npm start on my system: npm ERR! Failed at the purescript-starter-app@4.2.0 serve:watch script 'node ./webpack.config.js'.

ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve:watch"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! purescript-starter-app@4.2.0 serve:watch: `node ./webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript-starter-app@4.2.0 serve:watch script 'node ./webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript-starter-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript-starter-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript-starter-app
npm ERR! There is likely additional logging output above.

**Comment by Zenleaf** [comment]
node ./webpack.config.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'webpack-hot-middleware'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (~/example/webpack.config.js:106:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by alexmingoia** [comment]
Bleh... sorry about that. I forgot to commit some dependencies. Pull and do `npm install` and then `npm start` and you should be good.

**Comment by Zenleaf** [comment]
Yep that was it, thanks Alex :-)
